<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManagerMediatR.Contracts\TaskManagerMediatR.Contracts.csproj" />
    <ProjectReference Include="..\TaskManagerMediatR.Domain\TaskManagerMediatR.Domain.csproj" />
  </ItemGroup>

</Project>
